### ISSUE TITLE
Upgrade to libsass 3.3

### ISSUE THREAD

**Issue by irundaia** [bit3/jsass#13]
I've used libsass for a plugin for sbt. When checking which version of sass was supported, I noticed that jsass was still using version 3.2 of libsass while libsass 3.4 includes support for sass version 3.4.

Could you upgrade to libsass version 3.4?

**Comment by tristanlins** [comment]
Yes, but this may take a while. libsass 3.3 changed some thinks on the API... I take a look next weekend :-)

**Comment by irundaia** [comment]
If needed, I could take a look as well. Though I have to admit that my C experience isn't overly extensive.

**Comment by tristanlins** [comment]
I could not find any 3.4 release in the [libsass repository](https://github.com/sass/libsass)?!
The [release 3.3 issue](https://github.com/sass/libsass/issues/1453) is still open.

**Comment by irundaia** [comment]
You're absolutely correct! I apologise for the inconvenience. I did notice that [libsass 2.3](https://github.com/sass/libsass/releases) has been released three days ago (2.3.1 about an hour ago).

**Comment by tristanlins** [comment]
lol, they finished the 3.3 release immediate after my comment :-D

**Comment by tristanlins** [comment]
I started to use libsass 3.3 in the develop branch. But the unit tests are failling for the moment. I started to write some unit tests for the native api, because the problem seems to be deep inside the native world :-\

**Comment by tristanlins** [comment]
Done with #14
