### ISSUE TITLE
Support older JVM or document Java 1.8 requirement

### ISSUE THREAD

**Issue by Deraen** [bit3/jsass#15]
Hi,

I see that both pom.xml and build.gradle define target JDK version as 1.8. If 1.8 is required, would be great it was mentioned in the readme. If it's not strictly required, would be cool if jsass was compiled against older target JDK.

**Comment by tristanlins** [comment]
Jsass use some Java 8 features, like streams and lambdas. I will add a notice to the readme.

**Comment by tristanlins** [comment]
https://github.com/bit3/jsass#compatibility

**Comment by Deraen** [comment]
Thanks
