### ISSUE TITLE
Spaces in path

### ISSUE THREAD

**Issue by tristanlins** [bit3/jsass#17]
When there are spaces in the file path, there may be an UriSyntaxException, e.g. `Invalid character at index 16 in C:/Users/Tristan Lins/workspace/bit3/jsass/target/test-classes/scss/input.scss`

**Comment by irundaia** [comment]
Indeed, any URI should be encoded. Perhaps the [URLEncoder](http://docs.oracle.com/javase/8/docs/api/java/net/URLEncoder.html) provides a solution.

**Comment by larsgrefer** [comment]
The URI is created from String here: 
`io.bit3.jsass.importer.Import.<init>(Import.java:99)`

and converted back to String here:
`NativeImport.java:35`

**Comment by tristanlins** [comment]
thx @larsgrefer, fixed with #23
