### ISSUE TITLE
Different compilation results between OS X and Linux

### ISSUE THREAD

**Issue by larsgrefer** [bit3/jsass#21]
On OS X, fractions contain a leading `0`, but on Linux they don't

see #20 for details

**Comment by larsgrefer** [comment]
With [sassc](https://github.com/sass/sassc) I don't have the leading `0` on OS X

**Comment by irundaia** [comment]
Did you compile sassc from scratch, or did you use a tool like homebrew? If so, it might be the case that sassc is using libsass version 3.3.2 rather than version 3.3.3 that jsass is using. Could you verify that they are using the same version? If not, it is probably a regression in libsass.

**Comment by larsgrefer** [comment]
`sassc --version` says:

```
sassc: 3.3.0
libsass: 3.3.3
sass2scss: 1.0.5
```

**Comment by larsgrefer** [comment]
My sassc was using libsass 3.3.3, but jsass uses libsass 3.3.2 on osx.
Merge #29 in order to update the osx binaries to 3.3.3

**Comment by tristanlins** [comment]
Fixed by #30
