### ISSUE TITLE
Request: support FreeBSD

### ISSUE THREAD

**Issue by kyptin** [bit3/jsass#40]
I am trying to run `jsass`, but I use FreeBSD and I get the following exception:

    java.lang.UnsupportedOperationException: Platform freebsd:amd64 not supported

(This exception came from version 3.3.1 of `jsass`, but it looks like the code on master still does not support FreeBSD.)

My question: would it be possible to support FreeBSD?

Here are the files installed by the official `libsass` package on FreeBSD:

```
$ pkg list libsass
/usr/local/include/sass.h
/usr/local/include/sass_interface.h
/usr/local/lib/libsass.a
/usr/local/lib/libsass.so
/usr/local/lib/libsass.so.0
/usr/local/lib/libsass.so.0.0.0
/usr/local/libdata/pkgconfig/libsass.pc
/usr/local/share/licenses/libsass-1.0.1_2/LICENSE
/usr/local/share/licenses/libsass-1.0.1_2/MIT
/usr/local/share/licenses/libsass-1.0.1_2/catalog.mk
```

If it would be helpful, I can try my hand at a PR. But fair warning: it's been a while since I did any Java work. :-)

**Comment by tristanlins** [comment]
jsass comes with its own libsass binary, to prevent ABI breaks between the [jsass binaries](https://github.com/bit3/jsass/tree/master/src/main/c) and libsass binaries. I use docker containers to cross compile libsass + jsass C code for certain platforms, you can find these at [src/main/docker](https://github.com/bit3/jsass/tree/master/src/main/docker).

The java part is just a piece of cake.
The problem may be the cross compilation part.

I am of course willing to accept a PR for freebsd support :-)

Unfortunally [travis does not support freebsd](https://github.com/travis-ci/travis-ci/issues/1818) :-(
So far we must do this without CI tests ...

**Comment by kyptin** [comment]
OK, I will work on a PR. :-)

I'm trying to make sure my development environment\* works before I try adding a FreeBSD docker image, but I'm having some problems:

```
$ gradle buildNativeLibs
:determineCurrentWorkingDirectory
:determineDockerAvailable
:determineGid
:determineRepositoryHeadStability
:determineUid
:buildNativeDarwin64Libs
Build native libs for darwin x64
:buildNativeDarwin64Libs FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/jeff/code/vendor/jsass/build.gradle' line: 203

* What went wrong:
Execution failed for task ':buildNativeDarwin64Libs'.
> Docker run failed
  + cd /jsass/src/main
  + rm -r resources/darwin
  rm: cannot remove 'resources/darwin/libjsass.dylib': Permission denied
```

I ran the same gradle command with `--info`, which told me the docker command it was using:

    Starting process 'command 'docker''. Working directory: /Users/jeff/code/vendor/jsass Command: docker run --user=501:20 --rm -v /Users/jeff/code/vendor/jsass/.:/jsass bit3/jsass-build-darwin-x64:stable

I connected to the container in an interactive session, using mostly the same options, but apparently there was a problem with the `--user` flag, because:

```
$ docker run -it --user=501:20 --rm -v $PWD:/jsass bit3/jsass-build-darwin-x64:stable /bin/bash
I have no name!@67ed1f3edea0:/jsass$ whoami
whoami: cannot find name for user ID 501
I have no name!@67ed1f3edea0:/jsass$ touch hello
touch: cannot touch 'hello': Permission denied
```

So I tried doing the same command without the `--user` flag, and that connected as root, which seems more reasonable. So I removed the `--user` flag from the source in `build.gradle` and got a new problem:

```
$ gradle buildNativeLibs
:determineCurrentWorkingDirectory
:determineDockerAvailable
:determineGid
:determineRepositoryHeadStability
:determineUid
:buildNativeDarwin64Libs
Build native libs for darwin x64
:buildNativeDarwin64Libs FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/jeff/code/vendor/jsass/build.gradle' line: 204

* What went wrong:
Execution failed for task ':buildNativeDarwin64Libs'.
> Docker run failed
  + cd /jsass/src/main
  + rm -r resources/darwin
  + mkdir -p resources/darwin
  + make -C libsass clean
  make: Entering directory '/jsass/src/main/libsass'
  make: *** No rule to make target 'clean'.  Stop.
  make: Leaving directory '/jsass/src/main/libsass'
```

This makes sense, because there doesn't seem to be a `Makefile` in that directory:

```
$ docker run --rm -v $PWD:/jsass bit3/jsass-build-darwin-x64:stable ls /jsass/src/main
c
docker
java
libsass
resources
```

I suspect I'm doing something wrong. But I can't find anything in the readme or docs that tells me what I'm missing. Can you point me in the right direction? Thanks!

(I may be somewhat out of touch for the next few days, but I should be able to focus more on this starting Monday.)

\* My development environment is normally FreeBSD, but it turns out that FreeBSD's docker support is pretty limited so far (including not being able to mount volumes), so I resurrected an old iMac so that I could do development.

**Comment by tristanlins** [comment]
The `--user` part prevents the creation of root owned files in your user space working directory.

It seems you have forget updating the submodule in `src/main/libsass`. Make run with `-C libsass` which means the `Makefile` must be placed in the `libsass` directory.

**Comment by kyptin** [comment]
Ah, submodules, of course.

OK, after updating the submodule, I am getting farther along. But all 4 native libs still fail to build. The Darwin build and the Windows builds all fail at this step:

```
  make: Leaving directory `/jsass/src/main/libsass'
  + cp libsass/lib/libsass.dll resources/windows-x64/libsass.dll
  + rm -r c/build
  rm: cannot remove 'c/build': No such file or directory
```

I notice that this directory, `src/main/c/build`, is listed in the `.gitignore` file, which makes me think it should be generated somehow. But apparently it is not being generated. I think I'll try changing the `rm -r` to `rm -rf` to get past this error and see what happens. I'll report back.

Also, the Linux build failed here:

```
  g++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.4\"" -std=c++0x -I /jsass/src/main/libsass/include -fPIC -fPIC -c -o src/sass_interface.o src/sass_interface.cpp
  g++: internal compiler error: Killed (program cc1plus)
  Please submit a full bug report,
  with preprocessed source if appropriate.
  See <http://bugzilla.redhat.com/bugzilla> for instructions.
  g++ -Wall -O2 -DLIBSASS_VERSION="\"3.3.4\"" -std=c++0x -I /jsass/src/main/libsass/include -fPIC -fPIC -c -o src/sass2scss.o src/sass2scss.cpp
  make: *** [src/ast.o] Error 4
  make: *** Waiting for unfinished jobs....
  virtual memory exhausted: Cannot allocate memory
  make: *** [src/sass2scss.o] Error 1
  g++: internal compiler error: Killed (program cc1plus)
  Please submit a full bug report,
  with preprocessed source if appropriate.
  See <http://bugzilla.redhat.com/bugzilla> for instructions.
  make: *** [src/bind.o] Error 4
  g++: internal compiler error: Killed (program cc1plus)
  Please submit a full bug report,
  with preprocessed source if appropriate.
  See <http://bugzilla.redhat.com/bugzilla> for instructions.
  make: *** [src/color_maps.o] Error 4
  g++: internal compiler error: Killed (program cc1plus)
  Please submit a full bug report,
  with preprocessed source if appropriate.
  See <http://bugzilla.redhat.com/bugzilla> for instructions.
  make: *** [src/inspect.o] Error 4
  g++: internal compiler error: Killed (program cc1plus)
  Please submit a full bug report,
  with preprocessed source if appropriate.
  See <http://bugzilla.redhat.com/bugzilla> for instructions.
  make: *** [src/functions.o] Error 4
  make: Leaving directory `/jsass/src/main/libsass'
```

I don't understand this one. Maybe it was out of disk space in the docker container or something? Anyway, I'll look into it, time permitting.

**Comment by kyptin** [comment]
An update: I tried changing the `make.sh` files to say `rm -rf` instead of `rm -r`, but the change didn't seem to stick because `gradle buildNative<arch>Libs` still failed. But, when I created the `src/main/c/build` and `src/test/c/build` directories manually, that was enough to fix all the errors, and I can now build native libs for Darwin and Windows. I still get the same error for Linux and haven't had time to look into that further.

You might want to either create those directories in a prerequisite gradle task, or else change the make script to say `rm -rf`, to avoid other people having this problem in the future with a fresh clone.

I also tried to pull and run a FreeBSD docker image, but I haven't had much luck yet. Apparently, some of them only work on FreeBSD hosts, which is bizarre to me. I didn't know an image could be made like that! I don't know whether that's the case for all of them, and I don't know docker well enough to dig deeper. I think my next step is to read up more on docker then come back to this, but I have to quit for the week. I'm planning to pick this back up on Monday. Cheers!

**Comment by kyptin** [comment]
I tried every FreeBSD image on Docker Hub, and none of them run except on a FreeBSD host. (I left comments to that effect on Docker Hub, so that other people aren't surprised by this.)

So, even with docker, at present there doesn't appear to be any way to run a FreeBSD VM on a non-FreeBSD host. And with a FreeBSD host, there's no way to mount a volume in a docker container.

I can think of a few ways forward, despite these obstacles. First, the FreeBSD image could avoid mounting a volume and instead clone this repo afresh from Github when it's run. I suppose the Dockerfile would want to specify a particular commit to checkout. The downsides of this approach are (1) there'd be no (easy) way to test something without committing the change and pushing it to Github first, and (2) you could only run the image on a FreeBSD host, which most people don't have easy access to.

Another potential solution is to use a Linux image to cross-compile libsass for FreeBSD. But I'm not really sure how that would work or what all would be involved in a successful cross-compilation.

I suppose there may be some way to emulate a FreeBSD machine apart from docker, such as with VirtualBox or even something like `kvm` or `qemu`, but that sounds like a pretty involved task, and one that docker is specifically designed to avoid.

Lastly, I could just include FreeBSD's `libsass.so` library directly, as installed by the `pkg` tool. The downside here is that you (and other devs) wouldn't be able to build it yourself. I suppose also that you would need to trust that what I gave you was a legitimate library and not some hacked version. (Perhaps I could find the library file on an official FreeBSD server somewhere, if that's a concern.)

Of these options, the last one definitely sounds the simplest. But I don't know if the lack of auditability is a concern for you.

Please let me know what you think!

**Comment by kyptin** [comment]
OK, I've figured some things out.

First, docker isn't what I thought it was. I thought it provided a way to run docker images on any host that supported docker. But that's not strictly true, as it turns out. The interface between the docker image and the docker container is system calls, same as the interface between processes and the kernel. If you're on a Linux host and running a Linux image, you're effectively just running the docker image's process in a jail (or [cgroup](https://en.wikipedia.org/wiki/Cgroups)) so that it's isolated from other processes. If you're on a Mac OS X host and running a Linux image, that works too because you're actually running the image process inside the "Docker Machine", which is really (at least for me) just a Linux VM inside VirtualBox. (Windows has a similar story.) And a Linux image will also run fine on a FreeBSD host (apart from mounting volumes, which isn't supported yet—see above), because FreeBSD has a Linux compatibility layer that makes it able to respond properly to Linux system calls.

The surprising thing happens when you have a non-Linux docker image, such as [this relatively popular FreeBSD one](https://hub.docker.com/r/lexaguskov/freebsd/). Such an image _will only run on a FreeBSD host_. Why? Because the image's process will be making system calls, and Linux (i.e. the OS of the docker container) won't respond appropriately to what the FreeBSD process expects.

This means that, even if docker on FreeBSD gains support for mounting volumes, nobody but FreeBSD users will be able to build the libsass driver for FreeBSD.

That is, unless we jump through some major hoops. We could create a Linux docker image that starts a virtual machine hypervisor like KVM, then starts a FreeBSD VM inside the hypervisor, then passes commands from docker through the hypervisor to the FreeBSD VM. We'd also have to mount the volumes that the docker container would provide into KVM so that the FreeBSD OS could access them. (I'm assuming this is something that KVM can do, but I haven't actually looked into it.) Once we got all that working, we'd have a lot of complicated machinery just to run a FreeBSD host so that we could compile libsass and get a `libsass.so` file out.

At that point, why not just start with a `libsass.so` and skip all the machinery? The official one can be found here:

[http://pkg.freebsd.org/FreeBSD:10:amd64/latest/All/libsass-1.0.1_2.txz](http://pkg.freebsd.org/FreeBSD:10:amd64/latest/All/libsass-1.0.1_2.txz)

(Of course, when FreeBSD 11 comes out, you can change the `10` to `11`, and you can change the `amd64` to an alternate architecture.)

The contents of the archive include a `libsass.so` file that would be perfect for inclusion in jsass:

```
$ tar -tJvf libsass-1.0.1_2.txz                                      [16:21:22]
-rw-r--r--  0 root   wheel     689 Dec 31  1969 +COMPACT_MANIFEST
-rw-r--r--  0 root   wheel    1870 Dec 31  1969 +MANIFEST
-rw-r--r--  0 root   wheel     209 May 19 09:40 /usr/local/share/licenses/libsass-1.0.1_2/catalog.mk
-rw-r--r--  0 root   wheel      68 May 19 09:40 /usr/local/share/licenses/libsass-1.0.1_2/LICENSE
-rw-r--r--  0 root   wheel      84 May 19 09:40 /usr/local/share/licenses/libsass-1.0.1_2/MIT
-rw-r--r--  0 root   wheel    2742 May 19 09:40 /usr/local/include/sass.h
-rw-r--r--  0 root   wheel    1875 May 19 09:40 /usr/local/include/sass_interface.h
-rw-r--r--  0 root   wheel 3102966 May 19 09:40 /usr/local/lib/libsass.a
lrwxr-xr-x  0 root   wheel       0 May 19 09:40 /usr/local/lib/libsass.so -> libsass.so.0.0.0
lrwxr-xr-x  0 root   wheel       0 May 19 09:40 /usr/local/lib/libsass.so.0 -> libsass.so.0.0.0
-rwxr-xr-x  0 root   wheel 1046872 May 19 09:40 /usr/local/lib/libsass.so.0.0.0
-rw-r--r--  0 root   wheel     263 May 19 09:40 /usr/local/libdata/pkgconfig/libsass.pc
```

So, how about I add this `.so` file to jsass, add some code to support FreeBSD, and open a PR? :-)

**Comment by kyptin** [comment]
This issue is superseded by the PR of #42.
