### ISSUE TITLE
Add support for loggers

### ISSUE THREAD

**Issue by Glef** [bit3/jsass#41]
Hello,
Currently there is no way to change the logs output. For example, when an error occurs, the error is printed to system.err, without any option to prevent that.

It would be useful to have the option to specify a logger instead of forcing the standard output.

**Comment by tristanlins** [comment]
You can catch the [CompilationException](https://github.com/bit3/jsass/blob/master/src/main/java/io/bit3/jsass/CompilationException.java) and log the error output where you want it.
The error output from sass (e.g. `@error` or `@debug`) is printed to stdout/stderr by libsass itself. As far as I know, there is now way to change this behavior at the moment.

**Comment by Glef** [comment]
Thanks for your answer.
As a matter of fact, I was still using version 4.1.0, and my problem was fixed in version 5, with commit https://github.com/bit3/jsass/commit/9ad7c32eb659738055623db4ad97aea78fa90b21 
So my issue is indeed invalid, sorry for that.

**Comment by tristanlins** [comment]
+1
