### ISSUE TITLE
Use Webjar as scss source?

### ISSUE THREAD

**Issue by sisao** [bit3/jsass#43]
Hi,

is it possible to use jsass for building bootstrap from a webjar (https://github.com/webjars/bootstrap)?
The scss sources are located under META-INF/resources/... in the jar file...

Regards,
Stefan

**Comment by tristanlins** [comment]
You can use a custom [importer|https://github.com/bit3/jsass/blob/master/src/main/java/io/bit3/jsass/importer/Importer.java] to load a scss resource from wherever you want.

**Comment by sisao** [comment]
Thx for the fast response.

But I will have to load each dependent scss file seperatly?
A Importer for e.g. _variables.scss, and one for _mixins.scss?

**Comment by tristanlins** [comment]
The first parameter is the url to import, e.g. `variables` for `@import "variables";` or `mixins` for `@import "mixins";`. ;-)
