### ISSUE TITLE
libsass 3.4.x

### ISSUE THREAD

**Issue by jknack** [bit3/jsass#46]
any plans to supports latest libsass?

PS> I'm going to add a new assets module to http://jooby.org. There is a ruby sass processor already: http://jooby.org/doc/assets-sass/ but of course your library speed up everything ;)

**Comment by tristanlins** [comment]
Ist libsass 3.4 released? I cannot find it on https://github.com/sass/libsass/releases

**Comment by tristanlins** [comment]
And yes, jsass will support The latest libsass Version, if there is an official release ;-)

**Comment by jknack** [comment]
nevermind, was looking into the wrong place!

thanks again for jsass works perfectly.

**Comment by tristanlins** [comment]
No problem, you're welcome :-)
