### ISSUE TITLE
Does not output anything

### ISSUE THREAD

**Issue by gargomester** [bit3/jsass#49]
Tried using the simplest: http://jsass.readthedocs.io/en/latest/examples.html
Even though it says everything was fine, (it prints the compiled css to the console) it does not create the output file. 
When I tried the string version, it only showed the string's content at the console.

Included the latest lib through maven.
Am I missing something?

**Comment by tristanlins** [comment]
libsass does not produce an output file. The "outputFile" is used to calculate correct relative paths.

**Comment by gargomester** [comment]
Oh ok, so ideally I shall write the output.getCss() to a css file, right? but then why is the outputFile needed? Where is that relative path used if it doesn't write anything there?

**Comment by gargomester** [comment]
For some reason when I'm using the string version (http://jsass.readthedocs.io/en/latest/examples.html#compile-string)
for the output.getCss() I get this:

body {
  color: red; }

Shouldn't this part contain the compiled css plus the string which overrides the css?

**Comment by tristanlins** [comment]
What do you mean with "the string which overrides the css"? The sourcemap?

**Comment by tristanlins** [comment]
I must correct myself, if you use the `StringContext` no output file will be generated. If you use the `FileContext`, the given output file should be generated.
See https://github.com/bit3/jsass/blob/master/src/main/java/io/bit3/jsass/context/FileContext.java#L17

If not, this may be a bug :-D

**Comment by gargomester** [comment]
I actually tried both, none of them generated any file. 
Ideally I'd like to change some colours of the foundation scss file.
So I tried this:

        String input = "body { color: red; }";
        URI inputFile = new File("src/main/resources/static/scss/app.scss").toURI();
        URI outputFile = new File("stylesheet.css").toURI();
        Compiler compiler = new Compiler();
        Options options = new Options();
        try {
            Output output = compiler.compileString(input, inputFile, outputFile, options);
            try{
                PrintWriter p = new PrintWriter("stylesheet.css");
                p.append(output.getCss());
            }catch (Exception e){
                logger.info(e.getMessage());
            }
            System.out.println("Compiled successfully");
            System.out.println(output.getCss());
        } catch (CompilationException e) {
            System.out.println("Compile failed");
            System.out.println(e.getErrorText());
        }

As far as I know, this should generate a css from the scss file and include the string too, so the background colour is red.(I'd need to add here colour variables) But nothing is generated. 

Interestingly if I use the compileFile method then with the help of the printwriter I can generate css.

**Comment by tristanlins** [comment]
If you use `compiler.compileString`, the `input` source will be compiled, not the `inputFile` ;-)
When compiling sources from resources you must read the file within your java app like this:

```java
URI inputFile = new File("src/main/resources/static/scss/app.scss").toURI();
String input = IOUtils.toString(inputFile);
```

**Comment by gargomester** [comment]
So ideally the scss needs to be read into the input String variable and then any additional modifications shall be concatenated into that variable? Or what is the best approach to modify for example the $secondary-color of foundation?

**Comment by tristanlins** [comment]
This could be one way. The main problem of reading the file in Java is, that libsass cannot read the file from a JAR or WAR file. You can register your own [importer](http://jsass.readthedocs.io/en/latest/importers.html) to give libsass access to your webapp resources.

In our application we start the compiling with a source like this:

```scss
@import("vendor/foundation/foundation");
```

Our importer look like this

```java
public class MyImporter implements Importer {
  @Override
  public Collection<Import> apply(String url, Import previous) {
    try {
      URL resource = this.getClass().getResource("/assets" + url);
      return Collections.singletonList(
          new Import(
              new URI(url),
              resource, 
              IOUtils.toString(resource)
          )
      );
    } catch (URISyntaxException e) {
      throw new RuntimeException(e);
    }
  }
}
```

Foundation is placed in `/src/main/resources/assets/vendor/foundation`

**Comment by gargomester** [comment]
So libsass cannot import the files which are imported in the scss file if the application is packaged, right?
That's why the custom importer is needed. 
Or in this importer the path of the scss file need to be set?

**Comment by tristanlins** [comment]
libsass can import files from the regular filesystem by itself. But if you place scss files in your webapp war/jar archive, the file may not be accessible directly through the file system. In the last case you need a custom import, that can read the files libsass cannot access directly.

**Comment by gargomester** [comment]
Oh I see. In the meantime I tried to implement the importer.
Tried using yours however I'm getting an unhandled ioexception for this part IOUtils.toString(resource).

Plus tried this too:

public class CustomImporter implements Importer {
    @Override
    public Collection<Import> apply(String url, Import previous) {
        try {
            return Collections.singletonList(
                    new Import(
                            new URI("app.scss"),
                            new File("src/main/resources/static/scss/app.scss").toURI()
                    )
            );
        } catch (URISyntaxException e) {
            throw new RuntimeException(e);
        }
    }
}
However I'm using this file path for the inputFile too. 
If I'm using an importer then what shall be the inputFile's path?

Because I'm getting the following error: 
Compile failed
An @import loop has been found:

**Comment by gargomester** [comment]
Ok, found another compileString method that only needs a string and an option. I suppose when the importer is used then this compiler should be used with it. So I included the app.scss in the importer however I'm getting an Undefined variable: "$grey-50". error. 
This is a variable that should come from the file that is imported within the scss. So I guess it cannot import that for some reason. Any idea? At the moment I'm using the above importer.

**Comment by gargomester** [comment]
No, It actually imports the file from the scss, the problem I think is that it can't see the rest of the foundation files. Isn't there a way to set a directory into the whole directory?

**Comment by tristanlins** [comment]
I have create an example implementation of a minimalistic webapp:
https://github.com/bit3/jsass/tree/develop/example/webapp

I hope that it helps :-)
