### ISSUE TITLE
Where can I get OSGI bundle of jsass lib

### ISSUE THREAD

**Issue by kyyash** [bit3/jsass#55]
Hi Team,

I want to use jsass and was looking for 
Where can I get OSGI bundle of jsass lib ?  or do I need to bundelize myself.

**Comment by tristanlins** [comment]
I'm not familiar with OSGI and never created an OSGI bundle.
You may need to bundelize yourself.
The prebuild JARs including the native libs can be found on [maven central](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.bit3%22%20AND%20a%3A%22jsass%22).
