### ISSUE TITLE
Running in Alpine linux docker container?

### ISSUE THREAD

**Issue by sisao** [bit3/jsass#56]
When I'm trying to run jsass within a Tomcat in an Alpine linux docker container I get this message:

> ... /usr/local/tomcat/temp/libjsass-7263208612967937429/libjsass.so: Error relocating /usr/local/tomcat/temp/libjsass-7263208612967937429/libjsass.so: __strtod_internal: symbol not found

Is there a solution for this problem?
Do I have to compile my own libjsass for Alpine?

Regards,
Stefan

**Comment by tristanlins** [comment]
It seems that this is some kind of issue with alpines libc library, the node-sass guys have a similar issue, see https://github.com/sass/node-sass/issues/808#issuecomment-90248276
It seems that the native libs must be rebuild on alpine linux. The precompiled libs does not work :-/

**Comment by tristanlins** [comment]
@sisao can you try https://hub.docker.com/r/frolvlad/alpine-glibc/ instead of the official alpine container?

**Comment by sisao** [comment]
Ok, i'll try. Thx for the hint...

**Comment by sisao** [comment]
I had no luck with this one https://hub.docker.com/r/frolvlad/alpine-oraclejdk8/ but mabye I try again later if I can spare some time...
