### ISSUE TITLE
Watch directory for changes

### ISSUE THREAD

**Issue by sinuhepop** [bit3/jsass#57]
Sass has a very interesting feature for development. You can start a watcher service using `--watch` option:

`sass --watch app/sass:public/stylesheets`

This will start a monitoring service and when a Sass file is modified, all CSS depending on that file will be recompiled. It's important to observe that unaffected CSS won't be recompiled, which is obviously essential in a big project.

This feature is not present now in `jsass`, but AFAIK it must not be difficult to pass this option to the compiler. Anyway, I'm not experienced in JNI and don't know if starting a neverending command leads to problems.

**Comment by tristanlins** [comment]
> This feature is not present now in `jsass`, but AFAIK it must not be difficult to pass this option to the compiler.

I'm sorry to say, but it is difficult, becaus jsass is a library, not a compiler application.
The `sass` command is from the [ruby sass](https://github.com/sass/sass) compiler "application".
But jsass uses [libsass](https://github.com/sass/libsass) and both are just libraries, not applications. As a library, libsass does not have any file watching feature.

**Comment by sinuhepop** [comment]
Oh, didn't know about this difference between Sass and libsass. Interesting.

I'm planning to implement a watcher in Java (monitoring a folder, parsing `@import` for creating a dependency tree, etc). Let me know if you consider this can fit into `jsass` scope.

**Comment by tristanlins** [comment]
Currently jsass is designed to be just a library.
I'm not sure if this fit into jsass scope.
I see a problem, when using custom importers with jsass.
In my companies application, we have a similar "watch" logic integrated, but the scss files are collected from the filesystem, from jar files and from the database.
This is a bit more tricky than only watch some files on the filesystem ;-)
But if you wan't to publish your watcher somewhere, then I am glad to place a link in the README.

**Comment by tristanlins** [comment]
If you are interested, there is already a maven plugin, using jsass:
https://github.com/warmuuh/libsass-maven-plugin

**Comment by sinuhepop** [comment]
Yes, I know about that plugin. In fact, I discovered your library when looking at it :)

Certainly custom importers could be a problem. At first, it could work only when there are no custom importers or importers which only return `Import` containing files, not strings. Another option is an interface `CustomWatcher` that developers using custom importers must implement in order to use `WatcherService`. I'll think about it and I'll tell you.
