### ISSUE TITLE
Invalid Import-Package syntax error with maven-bundle-plugin

### ISSUE THREAD

**Issue by mickleroy** [bit3/jsass#59]
I'm running into an issue when using jsass 5.5.1 with the maven-bundle-plugin (i.e. makes a jar usable in an OSGI container). 

> [INFO] --- maven-bundle-plugin:2.5.3:bundle (default-bundle) @ aem-sass-compiler ---
[ERROR] Bundle com.github.mickleroy:aem-sass-compiler:bundle:1.0.1-SNAPSHOT : **The default package '.' is not permitted by the Import-Package syntax.** 
 This can be caused by compile errors in Eclipse because Eclipse creates 
valid class files regardless of compile errors.
The following package(s) import from the default package null
[ERROR] Error(s) found in bundle configuration

Please note this is not an issue with my project as it works fine with jsass 5.4.3. I traced this back to release 5.5.0, which introduced a `Main.class` in the package root. This causes the invalid bundle descriptor and is generally bad practice. 

>   inflating: io/bit3/jsass/type/TypeUtils.class  
  inflating: io/bit3/jsass/UnsupportedContextException.class  
  **inflating: Main.class**              
   creating: darwin/
  inflating: darwin/libjsass.dylib 

Thanks

**Comment by tristanlins** [comment]
I'm not sure where you find the `Main.class`, the current source does not contain a Main class in the default package.

**Comment by mickleroy** [comment]
It could be introduced by a transitive dependency. However, decompiling the class reveals some sort of integration testing logic:
```
import io.bit3.jsass.Compiler;
import io.bit3.jsass.Options;
import io.bit3.jsass.context.StringContext;
import java.net.URI;

public class Main {
    public Main() {
    }

    public static void main(String[] args) throws Exception {
        Options options = new Options();
        StringContext context = new StringContext("@debug 'Hello world';", new URI("file:///source.scss"), new URI("file:///target.css"), options);
        Compiler compiler = new Compiler();
        compiler.compile(context);
    }
}
```
Does this look familiar?

**Comment by tristanlins** [comment]
Oh ... this is a very old development file, before the junit tests exists.
I have deleted this class long time ago... but the `Main.class` file still exists in my build directory >.<
Run a `gradle clean build` removes the file ...
There is a new "clean" release 5.5.2 that should not contain the `Main.class`.
