### ISSUE TITLE
Call JSASS from an Ant task

### ISSUE THREAD

**Issue by SuperPat45** [bit3/jsass#62]
I need to compile a custom bootstrap 4 SASS file in an Ant Task.

For the old bootstrap3, I use the following ant task with the less4j API:
```
	<target name="compile LESS">
		<less less="bootstrap/less/bootstrap.less" css="bootstrap.css" />
	</target>
	<macrodef name="less">
		<attribute name="less" />
		<attribute name="css" />
		<sequential>
			<echo>Compiling @{less} ...</echo>
			<java classname="com.github.sommeri.less4j.commandline.CommandLine" failonerror="true">
				<classpath refid="build.classpath" />
				<arg value="${build.resources.dir}/src/@{less}" />
				<arg value="${build.resources.dir}/css/@{css}" />
			</java>
		</sequential>
	</macrodef>
```
Is it possible to do the same with JSASS for bootstrap 4 SASS file?

In other words, how to run JSASS compilation from an Ant task? I have not found any main method in JSASS...

**Comment by tristanlins** [comment]
JSASS is a library, not an application. Therefore, there is no main method.
You could try to use groovy, instead of an `<java>` task.
You can find an example how to compile a file here: http://jsass.readthedocs.io/en/latest/examples.html#compile-file

**Comment by SuperPat45** [comment]
It's pity. It will cost you nothing to add a simple class that takes two arguments.
