### ISSUE TITLE
documentation, how to upgrade lib-sass build steps

### ISSUE THREAD

**Issue by cancerberoSgx** [bit3/jsass#65]
I noticed there is no documentation to re-build jsass using a different (new) version of libsass. For example I would like to test jsass binding to the new libsass3.5.0 version (which include important performanc eimprovements) Is that possible ? If so, could you please indicate me how to do it barely so I can PL with a section in the readme about that? thanks!

**Comment by tristanlins** [comment]
Take a look into the [Gradle tasks you should know](https://github.com/bit3/jsass#gradle-tasks-you-should-know) section.

> `gradle buildNativeLibs` build the native libs, using our build docker container.

The only undocumented part is, that you need change the submodule `/src/main/libsass` to the version you want to build against.

BTW: libsass 3.5 isn't released yet or have I missed something?

**Comment by cancerberoSgx** [comment]
thanks, will follow the guide and PL the project if I see something missing.
