### ISSUE TITLE
LibSass upgrade to 3.5.0.beta.2

### ISSUE THREAD

**Issue by ThomasMaerkl** [bit3/jsass#66]
Hi,

we are currently having issues with node-sass producing different css output than your jsass lib. Reason is that node-sass 4.7.x includes libsass 3.5.0.beta.2 instead of your current 3.4.7. Downgrading node-sass does not seem a viable option to us, since our Web-Designer is of the opinion, that the output produced by libsass 3.5.0.beta.2 is more correct than that of 3.4.x.

Would you be willing to create a beta release of your jsass library which includes the 3.5.0.beta.2 libsass? And how much of a donation would you like to have for your efforts?

**Comment by tristanlins** [comment]
Unfortunately, the version 3.5 API has changed. Therefore, an upgrade is not so easy. But is there a reason why you need version 3.5.0.beta.2 and not 3.5.0.beta.3?

Generally I am not a friend of using a beta version. However, I am currently working on extracting the native library into separate subprojects. Then it would be no problem to support several different libsass versions.

**Comment by tristanlins** [comment]
Today I released jsass version 5.6 that includes libsass 3.5.2
