### ISSUE TITLE
Max CSS String size

### ISSUE THREAD

**Issue by AlexCraddock** [bit3/jsass#69]
Hello,

I have a large file to be compiled (well many files) with jsass, when I run Sassc from the CLI I get the output that I would expect, however when I do it through Java code, it doesn't return the complete String, it seems to be cutting off a number of characters. 

I was wondering is there a max file size (in terms of chars) that this library can return from the native compiler?

Regards,

Alex

**Comment by tristanlins** [comment]
Due to a loop error, we had the case that our CSS was 3.5 MB in size. ;-D
Theoretically, there should be no limit.

**Comment by AlexCraddock** [comment]
Strange, we seem to be having the end of the final CSS file being chopped off, I have debugged your code as much as I can, and when the css is populated in the Output object it doesn't have the complete string,

**Comment by tristanlins** [comment]
Maybe it's a problem with the platform? Which platform do you use? windows, unix, mac, x86, amd64?
Does the chopped string have a length of 2^x?

**Comment by AlexCraddock** [comment]
Apologies I am unsure what you mean with regards to the 2^x (I understand the notation just not the intention)

I am running my test on a mac, I used the latest version from maven central of the library.

I also have this set up 

sassc: 3.4.8
libsass: 3.5.2
sass2scss: 1.1.1
sass: 3.5


When I run the file through sass or sassc the file compiles correctly,

**Comment by tristanlins** [comment]
> Does the chopped string have a length of 2^x?

I mean, if the string (`String#getBytes()#length`) has a length of 1024, 2048, etc.
That would be an indication that somewhere overflow takes place.

**Comment by AlexCraddock** [comment]
Ah okay,

I have run my test code, with 3 different OutputSytles

503978 - Compressed - Seems to have all the CSS
641879 - Compact - is missing some
707710 - No mode set - is missing some,

**Comment by AlexCraddock** [comment]
Using the CLI - 
no mode set file size is 709561
Compact - 643599
Compressed - 505749

**Comment by tristanlins** [comment]
That's really strange. Unfortunately, I have no idea what's going on. Have you ever tried an older version?

Examples of jsass / libsass versions:
jsass version 5.5.6 -> libsass version 3.4.9
jsass version 5.5.5 -> libsass version 3.4.8
jsass version 5.5.4 -> libsass version 3.4.7

**Comment by AlexCraddock** [comment]
How does jsass know where libsass is to use? Is it using the one in this project or would it be using one that is on my OS?

**Comment by tristanlins** [comment]
jsass comes with its own version of libsass. ;-)

**Comment by AlexCraddock** [comment]
Out of interest I have just used the libsass-python library to test with, and that library is outputting the correct css. They are using libsass 3.5.2, when do you think you will be grading to a 3.5.* version?

**Comment by tristanlins** [comment]
> ...when do you think you will be grading to a 3.5.* version?

The 3.5 is relatively new. I already have the upgrade on my TODO list. Unfortunately I have to adjust the native component of jsass because the libsass API has changed ...

But to answer the question: in the near future ;-D

**Comment by AlexCraddock** [comment]
As an update, I have added a printf call inside the parse_and_execute method within the NativeAdapter.c

This is printing out the complete CSS to the STDOUT.

yet System.out.println(output.getCss()) still isn't.

I am going to continue digging.

**Comment by AlexCraddock** [comment]
` jstring j_cssT = (*env)->NewStringUTF(env, c_css);
	const char *str= (*env)->GetStringUTFChars(env,j_cssT,0);
	printf("%s",str);`

This is outputting my truncated String. So something between the const char* and jString creation is mucking it up

**Comment by AlexCraddock** [comment]
Hi @tristanlins I have found the cause of my issue and it's something that others might come up against.

The problem seems to be down to the way that the const char* is converted to a jstring.

It seems that if you use UTF-16 in your CSS, it's causing the jstring to create a shorter string than required.

https://imgur.com/a/6fTWT

In that screenshot you can see that we have non standard chars in the CSS. This is causing the final css coming back into the java code to be truncated.

A similar issue was raised here https://community.oracle.com/thread/1549869

I am not sure of the solution, but I will try to create a test for you as well so that you can see this in action.

This also seems to only affect the Java wrapper, as when I used python is worked fine. I didn't check any others though.

**Comment by AlexCraddock** [comment]
As a proof my css went from

#selectTags o
#selectTags ol {

When I removed a couple of the characters

**Comment by tristanlins** [comment]
Wow, great detective work!
The [GetStringUTFChars](https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/functions.html#wp17265) method interprets the characters as a UTF-8 string. For me it looks like a limitation of JNI ...
It is possible to change your encoding to UTF-8?

**Comment by AlexCraddock** [comment]
I agree it does look like a limitation of JNI, not sure what can be done, my C language skills are pretty weak. I am not sure if the Sass spec support UTF-16 but it's something to think about in the future.

Anyway, yes we are going to remove the icons in our CSS that were being used.

**Comment by discordier** [comment]
https://stackoverflow.com/a/32215302/4997506 might be a head up
