### ISSUE TITLE
Compilation issues while building jsass

### ISSUE THREAD

**Issue by gwfong** [bit3/jsass#71]
Hi. I'm trying to build jsass following the readme. When I run
>  gradle check
or
>  ./gradlew clean release

I get the following error:

> * What went wrong:
Could not determine the dependencies of task ':test'.
Could not resolve all dependencies for configuration ':jacocoAgent'.
Dependency lock state for configuration 'jacocoAgent' is out of date: Did not resolve 'org.jacoco:org.jacoco.agent:0.7.6.201602180812' which is part of the lock state

When I run
> gradle buildNativeLibs

I get
> * What went wrong:
Execution failed for task ':determineRepositoryHeadStability'.
> No signature of method: org.eclipse.jgit.internal.storage.file.FileRepository.getRef() is applicable for argument types: (java.lang.String) values: [HEAD]
  Possible solutions: getAt(java.lang.String), getFS(), grep(), exactRef(java.lang.String), findRef(java.lang.String), getAllRefs()

Ultimately, what I need to do is make changes in in the jsass C/C++ code such that they end up in the shared library used by the jsass jar. I'm not making any signature changes. 

I'm currently doing this on Linux Mint and Mac OS.

Is there something more I need to do to get the system to build following the readme?

Thanks

**Comment by tristanlins** [comment]
The first issue looks like a problem with the [dependency locking](https://github.com/bit3/jsass/commit/62c6e52e8f166c078aa396315c9d0bc04430a4a9). It was just an experiment with this new gradle feature. I removed the locks. Running `./gradlew check` works fine now.

The `buildNativeLibs` uses docker to build the native libs for all platforms.

For local development, you can use the `bin/make-libjsass-linux-x64-local.sh` or `bin/make-libjsass-darwin.sh` (even it is not named *-local.sh, it is still used for local development. I need to rename it some day).

btw `gradle release` is only used to create a new release version ;-)
For most of the gradle tasks, you need to clone the git repository. Downloading the zip will not work!

**Comment by gwfong** [comment]
Thanks. `./gradlew check` now works w/o issue like you said. The next problem is related to building libjsass. I tried `$ bin/make-libjsass-linux-x64.sh` and `./gradlew -t buildNativeLinux64Libs`

> Task :determineRepositoryHeadStability FAILED
FAILURE: Build failed with an exception.
Where: Build file '/home/gary/dev/jsass/projects/jsass/build.gradle' line: 164
What went wrong:
Execution failed for task ':determineRepositoryHeadStability'.
No signature of method: org.eclipse.jgit.internal.storage.file.FileRepository.getRef() is applicable for argument types: (java.lang.String) values: [HEAD]
  Possible solutions: getAt(java.lang.String), getFS(), grep(), exactRef(java.lang.String), findRef(java.lang.String), getAllRefs()

Searching around, I've seen references to a change to [grgit](https://github.com/ajoberstar/grgit/issues/229). I don't know the tool chain well enough to determine the fix might be.

The gradle method `determineRepositoryHeadStability` seems to be a way to just determine the type used in `runDockerContainer` which ultimately identifies the docker image. Is this correct? If the `grigit` issue cannot be resolved, can I just change build.gradle to build `latest` or `stable`? If so, which one is best?

**Comment by tristanlins** [comment]
After updating the grgit plugin, the `determineRepositoryHeadStability` task works again.
But compilation of the native libs failed ... looks like a problem with the docker container <.<

**Comment by tristanlins** [comment]
Okay, everythink works fine now.
I was fooled by Docker's pull policy....

For local development, I recommend working with make-libjsass-linux-x64-local.sh. The Docker based builds (buildNativeLibs * gradle tasks) are primarily for the releases. (but also work for local development)
