### ISSUE TITLE
I've got libjsass.so: ELF file OS ABI invalid

### ISSUE THREAD

**Issue by b3lowster** [bit3/jsass#74]
Hi

My operation system is following
LSB Version:	:core-3.1-amd64:core-3.1-noarch:graphics-3.1-amd64:graphics-3.1-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 5.5 (Tikanga)
Release:	5.5
Codename:	Tikanga

```
<dependency>
        <groupId>com.github.warmuuh</groupId>
        <artifactId>libsass-maven-plugin</artifactId>
        <version>0.2.10-libsass_3.5.3</version>
</dependency>
<dependency>
     	<groupId>io.bit3</groupId>
	<artifactId>jsass</artifactId>
	<version>5.7.3</version>
</dependency>
```
I've got the a following error:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/libjsass-643121989273620969/libjsass.so: /tmp/libjsass-643121989273620969/libjsass.so: ELF file OS ABI invalid
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
```

**Comment by tristanlins** [comment]
The error "ELF file OS ABI invalid" usually occurs when the cglib is incompatible. To build the binaries, [centos 6](https://github.com/bit3/jsass/blob/master/src/main/docker/build-linux-x64/Dockerfile#L1) is used (which in turn builds on RHEL 6). The system is with RHEL 5, or its cglib version is probably just too old.

All versions of jsass up to and including 5.5.6, however, still used [centos 5](https://github.com/bit3/jsass/blob/5.5.6/src/main/docker/build-linux-x64/Dockerfile#L1). With this version it could work on this machine.

**Comment by b3lowster** [comment]
Thanks a lot! It works for me!
