### ISSUE TITLE
Allow Android-style colors with alpha

### ISSUE THREAD

**Issue by LeoSchleicher** [bit3/jsass#76]
Hi,
I've fount that if I use Android-style colors with alpha component, such as #AAFF0000 the stylesheet does not compile. Is there any possibility to avoid this?

**Comment by tristanlins** [comment]
There is nothing jsass can do, because all the parsing is done by [libsass](https://github.com/sass/libsass).
But sass support a very similar syntax: `rgba(#aaff00, 0)`, see http://sass-lang.com/documentation/Sass/Script/Functions.html#rgba-instance_method

**Comment by LeoSchleicher** [comment]
Thank you! I would just say that original ruby and actual nodejs versions can parse these values  without any problems and value goes to the output as is.
