### ISSUE TITLE
All calls to compile.. exit with error code and no exception

### ISSUE THREAD

**Issue by tessoldroyd** [bit3/jsass#77]
Hi,

I am trying to run bit3 jsass on my Windows development box. I have tried a million different ways and all the jsass compilers. No matter what I do, every call to compile... (I've tried compileString(), compileFile(), FileContext.compile()) fails. The JVM stops running and exits with the following value:

Process finished with exit code -1073740940 (0xC0000374)

There is no stack trace or additional error message. I should mention that it runs fine on my Mac, and in our production environment. But it seems to be failing on multiple Windows machines.

Is there by chance a problem with the .dll? I have stepped through the code and it looks like my machine is trying to use the windows-x32 dlls.

Thanks,

Tess Oldroyd

**Comment by tristanlins** [comment]
Sounds like the vm crash. In the execution directory you should see a hs_err_pid* file. The file contains a native stack trace.

However, the windows 32 build is not (anymore) functional. This is also listed in the compatibility table.  
https://github.com/bit3/jsass#compatibility

**Comment by tessoldroyd** [comment]
Looks like my IDE was defaulting to the 32 bit JDK. I have updated this to use the 64 bit JDK and now it is running the windows 64 build. That fixed it.

Thanks for your help!
