### ISSUE TITLE
Failing CI

### ISSUE THREAD

**Issue by DanielRuf** [bit3/jsass#80]
https://travis-ci.org/bit3/jsass/jobs/405762724

**Comment by tristanlins** [comment]
This is not a bug.
The problem is that the OracleJDK URL is constantly changing and the tests are not updated every time.
Maybe I should switch to the OpenJDK LTS, because the URL does not change that often.

**Comment by tristanlins** [comment]
OK, now the unit tests fail on Java 11.
But I will not look at it until tomorrow O:-)

**Comment by tristanlins** [comment]
I moved the repository to Gitlab.
This repository remains as a mirror.
This ticket will [continue here](https://gitlab.com/jsass/jsass/issues/80).
