### ISSUE TITLE
Java 11

### ISSUE THREAD

**Issue by roofpig95008** [bit3/jsass#81]
Looks like jsass isn't on Java 11 yet. At a minimum, I think it needs the latest version of Jacoco (0.8.3).

That's an easy enough upgrade by itself (it would be a one-line pull request) but I'm wondering whether running the built-in tests would be sufficient to tell whether it works.

**Comment by tristanlins** [comment]
jsass works on java 11 (we use it in production in our company).
Only the build system fails on java 11.
I already noticed that [yesterday](https://github.com/bit3/jsass/issues/80#issuecomment-467539928) and will take a look at it today 😇

**Comment by tristanlins** [comment]
I moved the repository to Gitlab.
This repository remains as a mirror.
This ticket will [continue here](https://gitlab.com/jsass/jsass/issues/81).
